# Site settings
title: Daniel Heckrath
email: daniel@codeserv.de
description: My blog about programming related stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danielheckrath.github.io" # the base hostname & protocol for your site
twitter_username: tchackie
github_username:  DanielHeckrath

# Build settings
markdown: kramdown
